### ISSUE TITLE
Release into ROS Kinetic

### ISSUE THREAD

**Issue by 130s** [dornhege/rqt_paramedit#1]
AFAI see it's released up to ROS Indigo as of today.
If you need a help please let me know.
Thank you!

**Comment by dornhege** [comment]
If you have a Kinetic system that you could easily test if everything still works, that would be great. Otherwise there should be no issue with a Kinetic release.

**Comment by 130s** [comment]
I see.

@MauleshSTrivedi do you think you can check if this package works on Kinetic?

**Comment by MauleshSTrivedi** [comment]
@130s Thanks, I will look into it. As far as I am aware, `rqt_reconfigure` should be able to handle similar issues.

**Comment by dornhege** [comment]
I'm preparing a melodic release.
