### ISSUE TITLE
not found bin directory inside devel

### ISSUE THREAD

**Issue by LauraYan** [dornhege/rqt_paramedit#3]
Hi this maybe not a real issue, and I encountered this too for myself code, so my first question, after compiling the code, how can I run it?

**Comment by dornhege** [comment]
You should be able to just `rosrun qt_paramedit qt_paramedit`. Alternatively start rqt and select the ParamEdit plugin.

**Comment by LauraYan** [comment]
Thank you for your reply. I got it.
